### PR TITLE
Add strikethrough when rollback

### PR DESCRIPTION
**Pull request by rumickon**
rb

### CODE REVIEW

**Comment by rumickon** [comment]
Need to testing with non standard sql.
And 100 characters in Codacy is very few.

**Comment by Narimm** [comment]
As it stands there is no open issue that this really address's - I am not even sure what use it is yet.  I can sort of understand wanting to log rollbacks - however why they would appear in a report and how that would work and make sense hasnt been discussed.

**Comment by Bobcat00** [comment]
rumickon, can you provide a short description of how this change works?  It's not clear to me that the benefits are worth the additional complexity.

**Comment by rumickon** [comment]
I understand that solution is difficult. It’s difficult even for me now, because I did this pr almost two years ago in our fork of a prism and forgot a lot. ;)
Anyway it works and helps in administrating our server with partial rollbacks. And it helps to not repeat the rollback of the type item-insert, item-remove.
And there is similar functionality in coreprotect.
Hope someone can suggest a better solution. I just showed one of the version.

**Comment by rumickon** [comment]
This pr adds a new table. The rollbacked records are saved into this table. And a lot of code to just show records in the output.

**Pull request closed without merging**
