### PR TITLE
Remove the old PasteAPI and move paste to paste.gg - allows anon access.

### LINKED ISSUE #114: Remove the pasteAPI
I am not sure this api is even functional anymore and if anyone uses it -  

Additionally it presents issues if and when some moves to java 11.  It requires additional dependencies in that environment - 

I would appreciate community feedback

### PR DESCRIPTION
**Pull request by Narimm**
Pastes are set with 1hr expiry,

Closes #114 

Signed-off-by: Narimm <benjicharlton@gmail.com>

### CODE REVIEW

**Comment by Bobcat00** [comment]
Don't you also need to remove the following from PrismConfig.java?
```
// pste.me sharing.
config.addDefault("prism.paste.enable", false);
config.addDefault("prism.paste.username", "Username on http://pste.me/#/signup");
config.addDefault("prism.paste.api-key", "API key from http://pste.me/#/account");
```

**Comment by Narimm** [comment]
No because ....I havent removed paste  and eventually I will use the API key and paste enable.

**Comment by Narimm** [comment]
This could be pushed to 2.1.7 because we probably should get the logged for private pastes working  however this version allows anon pastes ...which means we can look at adding a debug paste

**Review by addstar — APPROVED** [review]
:+1: :clap: It's hard to review such a big change but as long as you've done the relevant testing, it's great you've been able retain this functionality for those who might want it. Nice work!! :clap:

**Comment by addstar** [comment]
Also love the idea of a "debug paste" for troubleshooting! :grin:

**Comment by Narimm** [comment]
I am bypassing codacy for this PR

**Pull request merged**
