### PR TITLE
Prism bukkit 180 - Paste reporting improvements, Moves joinevent processing async

### LINKED ISSUE #180: PlayerJoinEvent could be optimised
- Prism 2.1.6
- Paper 103
- Minecraft 1.15.2
- R5 3600 + 8GB RAM

As it currently stands, the PlayerJoinEvent in Prism is the 2nd biggest contributor to tick usage (when testing joining performance). The 1st is chunkAwait. 

image

I _think_ that the majority (if not all) of the [PlayerJoinEvent listener](https://github.com/AddstarMC/Prism-Bukkit/blob/a9fc716154591cac53ad73ce1688c1b709c35ceb/src/main/java/me/botsko/prism/listeners/PrismPlayerEvents.java#L115) could _probably_ be run asynchronously since, from what I can tell, it doesn't directly interact with the Bukkit API and is simply for caching. 

Would alleviate a bit (or a lot) of the impact placed upon servers during joining. Mostly beneficial for those that have a lot of people leaving/joining in short periods of time.

### PR DESCRIPTION
**Pull request by Narimm**
Improves paste reporting to include a deletion key
Also the join event handles that caches a player is now asynchronous

Closes #180

### CODE REVIEW

**Comment by Narimm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 6
           

Complexity increasing per file
==============================
- src/main/java/me/botsko/prism/listeners/PrismPlayerEvents.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/AddstarMC/Prism-Bukkit/pullRequest?prid=5546664&bid=18184227)

**Comment by Narimm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 6
           

Complexity increasing per file
==============================
- src/main/java/me/botsko/prism/listeners/PrismPlayerEvents.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/AddstarMC/Prism-Bukkit/pullRequest?prid=5546664&bid=18184227)

**Comment by Narimm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 6
           

Complexity increasing per file
==============================
- src/main/java/me/botsko/prism/listeners/PrismPlayerEvents.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/AddstarMC/Prism-Bukkit/pullRequest?prid=5546664&bid=18184227)

**Comment by Bobcat00** [comment]
Is it legal to call getConfig() from an async task?  I don't think so.

**Comment by addstar** [comment]
> Is it legal to call getConfig() from an async task? I don't think so.

I wondered that also, I've been looking for actual references to this and not having much like. All I can find is forum posts and no one seems to be in agreement. Some things in the Bukkit API are thread safe, but most are not. The `Configuration` object really just represents a set of HashMaps internally and considering they wont change during runtime, it's probably fine to access these options async, but I'm not 100% sure.

**Comment by Bobcat00** [comment]
I think the safe thing to do is make final variables with everything you need.  Since the config doesn't change, you can save the values you need in final variables.  There's also a reference to event which should be changed.

I'm assuming the final player object is OK to use.  I'm not really sure.

With C++, I discovered that none of the Standard Template Library functions are thread safe, even ones that don't make any changes. You can read my long story about that [here](https://www.spigotmc.org/threads/c-i-fixed-a-mistake-i-made-4-years-ago.417174/).

**Comment by addstar** [comment]
> I think the safe thing to do is make final variables with everything you need. Since the config doesn't change, you can save the values you need in final variables. There's also a reference to event which should be changed.

Yep this is the correct way to do things. You make final references first before launching the thread, then it's perfectly thread safe.. at least for the specific objects being referenced, but not objects that those final objects reference, if that makes sense?

**Comment by Bobcat00** [comment]
> but not objects that those final objects reference

Which is why I'm leery about Player.

**Comment by Narimm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
           

Complexity increasing per file
==============================
- src/main/java/me/botsko/prism/listeners/PrismPlayerEvents.java  1
         

Complexity decreasing per file
==============================
+ src/main/java/me/botsko/prism/players/PlayerIdentification.java  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/AddstarMC/Prism-Bukkit/pullRequest?prid=5546664&bid=18184227)

**Comment by Narimm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
           

Complexity increasing per file
==============================
- src/main/java/me/botsko/prism/listeners/PrismPlayerEvents.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/AddstarMC/Prism-Bukkit/pullRequest?prid=5546664&bid=18184227)

**Comment by Narimm** [comment]
Could you guys review the changes and comment we no longer access the player or config async

**Comment by Narimm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
           

Complexity increasing per file
==============================
- src/main/java/me/botsko/prism/listeners/PrismPlayerEvents.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/AddstarMC/Prism-Bukkit/pullRequest?prid=5546664&bid=18184227)

**Review by addstar — DISMISSED** [review]
:+1: Nice one :clap: Great stuff!

**Comment by Narimm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
           

Complexity increasing per file
==============================
- src/main/java/me/botsko/prism/listeners/PrismPlayerEvents.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/AddstarMC/Prism-Bukkit/pullRequest?prid=5546664&bid=18184227)

**Comment by Narimm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
           

Complexity increasing per file
==============================
- src/main/java/me/botsko/prism/listeners/PrismPlayerEvents.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/AddstarMC/Prism-Bukkit/pullRequest?prid=5546664&bid=18184227)

**Pull request merged**
