### PR TITLE
SoftDepend Multiverse-Core

### PR DESCRIPTION
**Pull request by Rothes**
Make sure Prism sets up custom worlds on enabling.

### CODE REVIEW

**Comment by Bobcat00** [comment]
Ah, is that why Prism didn't see 4 of my worlds?

**Comment by Rothes** [comment]
> Ah, is that why Prism didn't see 4 of my worlds?

Yeah I think so, if Prism is loaded before Multiverse-Core loaded in log.

**Comment by Rothes** [comment]
Also I think we should hook CreateWorld events?

**Review by addstar — APPROVED** [review]
:+1: Nice find, surprised this wasn't in place already :persevere:

**Comment by addstar** [comment]
> Also I think we should hook CreateWorld events?

Probably, but this would be more complex and could introduce bigger issues. Not sure it's worth the effort fixing ourselves.

**Pull request merged**
