### PR TITLE
Restore villagers type, level, offers

### PR DESCRIPTION
**Pull request by rumickon**
Restoring do not work for villagers with 1 level (novice).
Using Yaml for items serialization.
Need more testing.

### CODE REVIEW

**Comment by Narimm** [comment]
Hey Rumikon - serialization and deserialization is handled via json - no real need for Yaml here.

**Comment by Narimm** [comment]
I think the whole serialization interface needs upgrading to be more explicit in terms of requirements

**Comment by rumickon** [comment]
> Hey Rumikon - serialization and deserialization is handled via json - no real need for Yaml here.

Json deserialization cannot restore ItemMeta.

**Comment by rumickon** [comment]
Can someone implement it in a different way? With restoring enchantments, lore, etc.

**Comment by addstar** [comment]
@rumickon I just wanted to say thanks for your submissions (we know there's been several), we really appreciate the contributions to Prism and glad you're helping make it better :slightly_smiling_face: 

Regarding this change, we need to think a little more about how the serialisation happens before accepting this. All the serialisation throughout prism uses json, so we're not too keen to use an do it a different way just for villagers. We'll look into things and get back to you when we can.

**Comment by rumickon** [comment]
Maybe this will help make a solution: https://hub.spigotmc.org/jira/browse/SPIGOT-5600?focusedCommentId=36155#comment-36155

**Comment by Narimm** [comment]
We are going to close this one with a view to future

**Pull request closed without merging**
