### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by Narimm**

### CODE REVIEW

**Comment by addstar** [comment]
No description? What is this for? Is there some automation for this or is it purely just a text file we update?

**Comment by Narimm** [comment]
Its to meet githubs policy of telling people how to lodge security issues.

Yep just a non code text file

**Comment by Narimm** [comment]
https://github.com/AddstarMC/Prism-Bukkit/blob/f4452f499dc36bf11aea39c094e9c70418c57c4f/SECURITY.md

**Review by addstar — APPROVED** [review]

**Review by alchemistmatt — APPROVED** [review]
:white_check_mark: is new to me; ah, emoji: https://gist.github.com/rxaviers/7360908

**Pull request merged**
