### PR TITLE
fix spigot repo/dependencies

### PR DESCRIPTION
**Pull request by PhanaticD**

### CODE REVIEW

**Comment by Narimm** [comment]
I am not entirely sure why you felt the need to add a direct dependency on bukkit...its in spigot already.

**Comment by PhanaticD** [comment]
idk

**Comment by viveleroi** [comment]
I assumed there were specific reasons and wasn't going to bring it up when I reviewed this but "idk" isn't very compelling. If it's not needed, I'll remove it, or approve a PR to.

**Comment by PhanaticD** [comment]
I did it because it was still using bukkit 1.7 API when I tried to compile it, but if you say that it not the case anymore then go ahead

**Pull request merged**
